"""Cross-language parity gate: Python DAG aggregators vs the TS SpecForge engine.

Loads every committed ``fixtures/golden/dag/*.json`` (generated by
``tools/gen_dag_golden.mjs`` from the genuine TypeScript tree aggregators),
reconstructs the Python inputs (:class:`TicketNode` / :class:`EpicNode` /
:class:`DepEdge`), runs the matching :mod:`specsmither.dag` function, normalizes
the Python output to the TS-shaped dict (camelCase keys; ``generatedAt`` /
``version`` / epic ``status`` dropped — the pure-DAG tree intentionally omits
epic status), and asserts byte-for-byte equality with the fixture ``expected``.

CI runs no Node; the fixtures are committed and THIS test is the gate. Each
fixture pins a determinism trap that, if the port drifted, would diverge:

* ``critical_path_lexless`` — lexLess tie-break: equal-minute paths pick the
  lexicographically smaller id-list (``[n1, n3]``, not ``[n2, n3]``).
* ``critical_path_zero_weight`` — a ``0`` / missing estimate weighs **1** in path
  selection (``0 -> 1`` / ``None -> 1``).
* ``build_tree_undefined_zero`` — display split: a *missing* estimate renders/sums
  as ``60`` (``?? 60``) but a literal ``0`` renders ``0``.
* ``build_tree_halfup`` — ``criticalPathMinutes`` rounds half **up** (``32.5 ->
  33``); Python banker's ``round`` would give ``32`` and fail here.
* ``find_cycles_scc_selfloop`` — a 2-node SCC + a self-loop (+ a 3-cycle), each
  cycle sorted and the result sorted by ``cycle[0]``.
* ``blocker_depth_done_terminator`` — a ``done`` dependency is dropped and
  terminates the incomplete-blocker chain.
* ``build_tree_basic`` — a full small spec: ready/blocked split and the
  ``(ticketNumber, id)`` ordering of ``readyTickets`` / epic ``ticketIds``.
"""

from __future__ import annotations

import json
from collections.abc import Callable
from pathlib import Path
from typing import Any

import pytest

from specsmither.dag.critical_path import (
    compute_critical_path,
    compute_max_blocker_depth,
    find_cycles,
)
from specsmither.dag.tree import (
    CriticalPathNode,
    DependencyTree,
    ExtendedTreeSummary,
    TreeTicket,
    build_dependency_tree,
)
from specsmither.dag.types import DepEdge, EpicNode, TicketNode

# Pin generatedAt to the same instant the generator used; it is stripped anyway.
_FIXED_NOW = "2026-06-26T00:00:00.000Z"

FIXTURE_DIR = Path(__file__).resolve().parent.parent / "fixtures" / "golden" / "dag"


# --- input reconstruction ----------------------------------------------------


def _edges(raw: Any) -> list[DepEdge]:
    return [DepEdge(ticket_id=e["ticketId"], depends_on_id=e["dependsOnId"]) for e in raw]


def _run_critical_path(inp: Any) -> dict[str, Any]:
    tickets = [
        TicketNode(id=n["id"], status="pending", estimated_minutes=n.get("estimatedMinutes"))
        for n in inp["nodes"]
    ]
    res = compute_critical_path(
        tickets, _edges(inp["edges"]), exclude=frozenset(inp.get("excludedIds", []))
    )
    return {"path": [n.id for n in res.path], "minutes": res.minutes}


def _run_blocker_depth(inp: Any) -> dict[str, Any]:
    tickets = [TicketNode(id=n["id"], status=n["status"]) for n in inp["nodes"]]
    depth = compute_max_blocker_depth(
        tickets, _edges(inp["edges"]), exclude=frozenset(inp.get("excludedIds", []))
    )
    return {"maxDepth": depth}


def _run_find_cycles(inp: Any) -> list[list[str]]:
    return find_cycles(list(inp["nodeIds"]), _edges(inp["edges"]))


def _run_build_tree(inp: Any) -> dict[str, Any]:
    epics = [
        EpicNode(id=e["id"], epic_number=e.get("epicNumber"), title=e.get("title"))
        for e in inp["epics"]
    ]
    tickets = [
        TicketNode(
            id=t["id"],
            status=t["status"],
            estimated_minutes=t.get("estimatedMinutes"),
            epic_id=t.get("epicId"),
            ticket_number=t.get("ticketNumber"),
            title=t.get("title"),
        )
        for t in inp["tickets"]
    ]
    tree = build_dependency_tree(
        inp["specificationId"],
        epics,
        tickets,
        _edges(inp["dependencies"]),
        previous_version=inp.get("previousVersion"),
        generated_at=_FIXED_NOW,
    )
    return _serialize_tree(tree)


# --- TS-shaped normalization of the Python tree output -----------------------


def _serialize_cp_node(n: CriticalPathNode) -> dict[str, Any]:
    return {
        "id": n.id,
        "ticketNumber": n.ticket_number,
        "title": n.title,
        "estimatedMinutes": n.estimated_minutes,
    }


def _serialize_ticket(t: TreeTicket) -> dict[str, Any]:
    out: dict[str, Any] = {
        "id": t.id,
        "ticketNumber": t.ticket_number,
        "title": t.title,
        "status": t.status,
        "epicId": t.epic_id,
        "epicNumber": t.epic_number,
        "dependencies": list(t.dependencies),
        "blocks": list(t.blocks),
        "isReady": t.is_ready,
        "blockerCount": t.blocker_count,
        "unsatisfiedDeps": list(t.unsatisfied_deps),
    }
    # Optional field: None is omitted (matching JSON.stringify dropping undefined);
    # a literal 0 is kept.
    if t.estimated_minutes is not None:
        out["estimatedMinutes"] = t.estimated_minutes
    return out


def _serialize_summary(s: ExtendedTreeSummary) -> dict[str, Any]:
    return {
        "totalTickets": s.total_tickets,
        "ticketsByStatus": {
            "pending": s.tickets_by_status.pending,
            "ready": s.tickets_by_status.ready,
            "active": s.tickets_by_status.active,
            "done": s.tickets_by_status.done,
        },
        "readyTickets": list(s.ready_tickets),
        "blockedTickets": list(s.blocked_tickets),
        "hasCircularDeps": s.has_circular_deps,
        "criticalPathLength": s.critical_path_length,
        "criticalPathMinutes": s.critical_path_minutes,
        "maxBlockerDepth": s.max_blocker_depth,
        "criticalPath": [_serialize_cp_node(n) for n in s.critical_path],
        "estimatedMinutesTotal": s.estimated_minutes_total,
    }


def _serialize_tree(tree: DependencyTree) -> dict[str, Any]:
    return {
        "specificationId": tree.specification_id,
        "epics": [
            {
                "id": e.id,
                "epicNumber": e.epic_number,
                "title": e.title,
                "ticketIds": list(e.ticket_ids),
            }
            for e in tree.epics
        ],
        "tickets": {tid: _serialize_ticket(t) for tid, t in tree.tickets.items()},
        "summary": _serialize_summary(tree.summary),
        "criticalPath": [_serialize_cp_node(n) for n in tree.critical_path],
        "edges": [{"from": e.from_, "to": e.to} for e in tree.edges],
        "cycles": [{"cycle": list(c.cycle)} for c in tree.cycles],
    }


_RUNNERS: dict[str, Callable[[Any], Any]] = {
    "critical_path": _run_critical_path,
    "blocker_depth": _run_blocker_depth,
    "find_cycles": _run_find_cycles,
    "build_tree": _run_build_tree,
}

_FIXTURES = sorted(FIXTURE_DIR.glob("*.json"))


def test_fixtures_present() -> None:
    """Guard against an empty glob silently passing the parametrized gate."""
    assert _FIXTURES, f"no DAG golden fixtures found under {FIXTURE_DIR}"


@pytest.mark.parametrize("fixture_path", _FIXTURES, ids=lambda p: p.stem)
def test_dag_golden(fixture_path: Path) -> None:
    data: Any = json.loads(fixture_path.read_text())
    actual = _RUNNERS[data["kind"]](data["input"])
    assert actual == data["expected"]
