"""Cross-language parity gate: the Python TOON encoder vs the TS reference.

Loads every committed ``fixtures/golden/toon/*.json`` (generated by
``tools/gen_toon_golden.mjs`` from the genuine ``@toon-format/toon`` v2.1.0
``encode``), runs :func:`specsmither.toon.encode` on the fixture ``input`` with
its optional ``options``, and asserts the output equals the fixture ``expected``
**byte-for-byte**.

The fixture ``input`` is the JS->JSON canonical bridge: the generator wrote it
via ``JSON.stringify``, so reading it back pins the exact JS-normalized value
(number formatting, ``-0`` collapse, integer-key ordering) the TS encoder saw.

CI runs no Node; the fixtures are committed and THIS test is the gate. The cases
span TOON's full encode surface: scalars and JS number formatting, nested
objects, empty ``{}`` / ``[]``, deep nesting, tabular arrays of uniform objects
(with field/value quoting), ragged / mixed-key / non-primitive arrays as list
items, arrays of primitives and arrays of arrays, objects nested in list items,
every string-quoting trigger (delimiter / newline / quote / backslash / tab /
colon / brackets / braces / leading hyphen / surrounding whitespace /
numeric-like / leading zero / bool-or-null-like) plus unicode, the tab and pipe
delimiters, ``indent=4``, and safe key folding (with ``flatten_depth``).
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pytest

from specsmither.toon import encode

FIXTURE_DIR = Path(__file__).resolve().parent.parent / "fixtures" / "golden" / "toon"

_FIXTURES = sorted(FIXTURE_DIR.glob("*.json"))


def test_fixtures_present() -> None:
    """Guard against an empty glob silently passing the parametrized gate."""
    assert _FIXTURES, f"no TOON golden fixtures found under {FIXTURE_DIR}"


@pytest.mark.parametrize("fixture_path", _FIXTURES, ids=lambda p: p.stem)
def test_toon_golden(fixture_path: Path) -> None:
    data: Any = json.loads(fixture_path.read_text(encoding="utf-8"))
    options: dict[str, Any] = data.get("options", {})
    actual = encode(data["input"], **options)
    assert actual == data["expected"]
