"""Engine / session / transaction contract for the SQLite persistence layer.

This is the foundation every ORM model and repository builds on. It owns:

* :class:`Base` — the single declarative registry (one ``MetaData`` shared by
  every model) with a deterministic ``naming_convention`` so index/constraint
  names are stable across machines and migrations.
* :class:`JSONType` — a ``dict``/``list`` ⇄ ``TEXT`` codec (SQLite has no native
  JSON type; we store compact JSON text and decode on read).
* :func:`new_ulid` / :func:`now_iso` — the id and timestamp generators (ULID
  string PKs; ISO-8601 UTC string timestamps).
* :class:`IdMixin` / :class:`TimestampMixin` — the shared PK + audit columns.
* :func:`make_engine` — a correctly-configured SQLite engine. The two event
  listeners are the load-bearing part: ``isolation_level = None`` hands BEGIN
  control to us, and a ``BEGIN IMMEDIATE`` on every transaction takes the write
  lock *up front* (the single-writer invariant; see architecture §4a). Without
  both, pysqlite defers BEGIN to the first DML (DEFERRED) and a racing second
  writer would not hit the write lock immediately.
* :func:`make_session_factory` — the ``sessionmaker`` (``expire_on_commit=False``
  so committed instances stay usable for building MCP responses).

No models live here.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from sqlalchemy import MetaData, String, Text, create_engine, event
from sqlalchemy.engine import Connection, Engine
from sqlalchemy.engine.interfaces import Dialect
from sqlalchemy.orm import (
    DeclarativeBase,
    Mapped,
    Session,
    mapped_column,
    sessionmaker,
)
from sqlalchemy.types import TypeDecorator

# new_ulid / now_iso live in the dependency-free leaf specsmither.ids so pure modules
# can mint ids/timestamps without pulling sqlalchemy transitively. Re-imported here
# because IdMixin/TimestampMixin column defaults need them; re-exported (see __all__)
# so ``from specsmither.db.base import new_ulid, now_iso`` keeps working.
from specsmither.ids import new_ulid, now_iso

__all__ = [
    "Base",
    "IdMixin",
    "JSONType",
    "TimestampMixin",
    "make_engine",
    "make_session_factory",
    "new_ulid",
    "now_iso",
]


# Deterministic index/constraint naming. Keeping these stable means a migration's
# DDL and the ORM-reflected schema agree byte-for-byte regardless of declaration
# order or platform — autogenerated names (SQLite's anonymous constraints) would
# drift otherwise.
_NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """The single declarative base. Every model shares this ``MetaData`` registry.

    Cross-file foreign keys and relationships therefore resolve by string name
    (``"tickets.id"`` / ``"Ticket"``) against this one registry.
    """

    metadata = MetaData(naming_convention=_NAMING_CONVENTION)


class JSONType(TypeDecorator[Any]):
    """A ``dict``/``list`` ⇄ JSON-``TEXT`` column codec for SQLite.

    Stored as compact JSON (no spaces, ``ensure_ascii=False`` so non-ASCII stays
    human-readable in the file). ``None`` round-trips as SQL ``NULL`` — it is not
    encoded as the JSON literal ``null``.
    """

    impl = Text
    cache_ok = True

    def process_bind_param(self, value: Any, dialect: Dialect) -> str | None:
        if value is None:
            return None
        return json.dumps(value, separators=(",", ":"), ensure_ascii=False)

    def process_result_value(self, value: Any, dialect: Dialect) -> Any:
        if value is None:
            return None
        return json.loads(value)


class IdMixin:
    """Adds the ULID string primary key. Each subclass gets its own column copy."""

    id: Mapped[str] = mapped_column(String(26), primary_key=True, default=new_ulid)


class TimestampMixin:
    """Adds ISO-8601 string ``created_at`` / ``updated_at`` audit columns.

    ``updated_at`` is refreshed on every UPDATE via ``onupdate``. Append-only
    audit rows do not use this mixin; they carry a ``created_at``-only column.
    """

    created_at: Mapped[str] = mapped_column(default=now_iso)
    updated_at: Mapped[str] = mapped_column(default=now_iso, onupdate=now_iso)


def make_engine(
    path: str | Path,
    *,
    busy_timeout_ms: int = 5000,
    echo: bool = False,
) -> Engine:
    """Build a SQLite engine wired for the single-writer / WAL concurrency model.

    Two event listeners carry the contract:

    * ``"connect"`` — sets ``isolation_level = None`` (disables pysqlite's
      implicit BEGIN so *we* control transaction start), then applies
      ``PRAGMA foreign_keys=ON``, ``journal_mode=WAL`` and ``busy_timeout`` to
      every pooled connection.
    * ``"begin"`` — issues ``BEGIN IMMEDIATE`` so the write lock is acquired at
      transaction start, not deferred to the first DML. A racing second writer
      then hits the lock immediately (waits ``busy_timeout`` then fails), which
      is the multi-process form of the one-active-session invariant.
    """
    engine = create_engine(f"sqlite+pysqlite:///{path}", echo=echo)

    @event.listens_for(engine, "connect")
    def _configure_connection(dbapi_conn: Any, _record: Any) -> None:
        # CRITICAL: hand BEGIN control to us — otherwise pysqlite emits a
        # DEFERRED BEGIN on the first DML and the write lock is taken late.
        dbapi_conn.isolation_level = None
        cursor = dbapi_conn.cursor()
        try:
            cursor.execute("PRAGMA foreign_keys=ON")
            cursor.execute("PRAGMA journal_mode=WAL")
            cursor.execute(f"PRAGMA busy_timeout={busy_timeout_ms}")
        finally:
            cursor.close()

    @event.listens_for(engine, "begin")
    def _begin_immediate(conn: Connection) -> None:
        conn.exec_driver_sql("BEGIN IMMEDIATE")

    return engine


def make_session_factory(engine: Engine) -> sessionmaker[Session]:
    """Return the ``sessionmaker`` bound to *engine* (instances survive commit)."""
    return sessionmaker(bind=engine, expire_on_commit=False)
